/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ACCS.java
 *
 * Created on 10.06.2012., 14.34.01
 */
package rs.etf.prv.accs;

/**
 *
 * @author MB
 */
public class ACCS extends javax.swing.JPanel {

    private final static String strStartEngine = "Start Engine";
    private final static String strStopEngine = "Stop Engine";
    private final static String strApplyBrake = "Apply Brake";
    private final static String strReleaseBrake = "Release Brake";
    private final static String strTopGearEngaged = "Engage Top Gear";
    private final static String strTopGearDisengaged = "Disengage Top Gear";
    private final static int commandActivate = 0;
    private final static int commandDeactivate = 1;
    private final static int commandStartAcc = 2;
    private final static int commandStopAcc = 3;
    private final static int commandResume = 4;
    private boolean engineOn = false;
    private boolean topGearEngaged = false;
    private boolean brakeApplied = false;

    /** Creates new form ACCS */
    public ACCS() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textFieldSpeedW = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        textFieldSpeed = new javax.swing.JTextField();
        textFieldThrottle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCommandLeverSensorActivate = new javax.swing.JButton();
        textFieldSpeedA = new javax.swing.JTextField();
        btnCommandLeverSensorResume = new javax.swing.JButton();
        btnCommandLeverSensorStopAcceleration = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCommandLeverSensorStartAcceleration = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCommandLeverSensorDeactivate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSetManualSpeed = new javax.swing.JButton();
        toggleBtnTopGear = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        toggleBtnEngine = new javax.swing.JToggleButton();
        toggleBtnBrake = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblCurrSpped = new javax.swing.JLabel();
        lblACCSVoltage = new javax.swing.JLabel();
        lblLastSavedSpeed = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textFieldThrottleA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textFieldThrootleW = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSetSpeed = new javax.swing.JButton();
        btnSetThrottle = new javax.swing.JButton();
        btnSetManualThrottle = new javax.swing.JButton();
        lblActualVoltage = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        jLabel14.setText("Last saved speed:");

        jLabel12.setText("V");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("Values from ACCS");

        jLabel17.setText("Error message:");

        jLabel15.setText("ACCS voltage:");

        jLabel16.setText("Actual voltage:");

        jLabel20.setText("Throttle");

        jLabel19.setText("*t)");

        textFieldSpeedW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldSpeedW.setText("0.005");

        jLabel18.setText("*sin(");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 48));
        jLabel7.setText("km/h");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("Parameters");

        jLabel8.setText("Set Speed");

        textFieldSpeed.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        textFieldThrottle.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel9.setText("Set Throttle");

        btnCommandLeverSensorActivate.setText("Activate");
        btnCommandLeverSensorActivate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCommandLeverSensorActivate.setEnabled(false);
        btnCommandLeverSensorActivate.setMaximumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorActivate.setMinimumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorActivate.setPreferredSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandLeverSensorActivateActionPerformed(evt);
            }
        });

        textFieldSpeedA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldSpeedA.setText("200");
        textFieldSpeedA.setEnabled(false);
        textFieldSpeedA.setFocusable(false);
        textFieldSpeedA.setMaximumSize(new java.awt.Dimension(24, 20));
        textFieldSpeedA.setMinimumSize(new java.awt.Dimension(24, 20));

        btnCommandLeverSensorResume.setText("Resume");
        btnCommandLeverSensorResume.setEnabled(false);
        btnCommandLeverSensorResume.setMaximumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorResume.setMinimumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorResume.setPreferredSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandLeverSensorResumeActionPerformed(evt);
            }
        });

        btnCommandLeverSensorStopAcceleration.setText("Stop Acceleration");
        btnCommandLeverSensorStopAcceleration.setEnabled(false);
        btnCommandLeverSensorStopAcceleration.setMaximumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorStopAcceleration.setMinimumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorStopAcceleration.setPreferredSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorStopAcceleration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandLeverSensorStopAccelerationActionPerformed(evt);
            }
        });

        jLabel11.setText("km/h");

        btnCommandLeverSensorStartAcceleration.setText("Start Acceleration");
        btnCommandLeverSensorStartAcceleration.setEnabled(false);
        btnCommandLeverSensorStartAcceleration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandLeverSensorStartAccelerationActionPerformed(evt);
            }
        });

        jLabel10.setText("Speed");

        btnCommandLeverSensorDeactivate.setText("Deactivate");
        btnCommandLeverSensorDeactivate.setEnabled(false);
        btnCommandLeverSensorDeactivate.setMaximumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorDeactivate.setMinimumSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorDeactivate.setPreferredSize(new java.awt.Dimension(119, 23));
        btnCommandLeverSensorDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandLeverSensorDeactivateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Command Lever Sensor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 48));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Current Speed");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setFocusable(false);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnSetManualSpeed.setText("Set");
        btnSetManualSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetManualSpeedActionPerformed(evt);
            }
        });

        toggleBtnTopGear.setText("Engage Top Gear");
        toggleBtnTopGear.setMaximumSize(new java.awt.Dimension(119, 23));
        toggleBtnTopGear.setMinimumSize(new java.awt.Dimension(119, 23));
        toggleBtnTopGear.setPreferredSize(new java.awt.Dimension(119, 23));
        toggleBtnTopGear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtnTopGearActionPerformed(evt);
            }
        });

        jSeparator3.setMaximumSize(new java.awt.Dimension(50, 10));

        toggleBtnEngine.setText("Start Engine");
        toggleBtnEngine.setMaximumSize(new java.awt.Dimension(119, 23));
        toggleBtnEngine.setMinimumSize(new java.awt.Dimension(119, 23));
        toggleBtnEngine.setPreferredSize(new java.awt.Dimension(119, 23));
        toggleBtnEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtnEngineActionPerformed(evt);
            }
        });

        toggleBtnBrake.setText("Apply Brake");
        toggleBtnBrake.setMaximumSize(new java.awt.Dimension(119, 23));
        toggleBtnBrake.setMinimumSize(new java.awt.Dimension(119, 23));
        toggleBtnBrake.setOpaque(true);
        toggleBtnBrake.setPreferredSize(new java.awt.Dimension(119, 23));
        toggleBtnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtnBrakeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Top Gear");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Brake");

        lblCurrSpped.setFont(new java.awt.Font("Tahoma", 1, 48));
        lblCurrSpped.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurrSpped.setText("0");

        lblACCSVoltage.setText("0 V");
        lblACCSVoltage.setFocusable(false);
        lblACCSVoltage.setRequestFocusEnabled(false);

        lblLastSavedSpeed.setText("140 km/h");
        lblLastSavedSpeed.setFocusable(false);
        lblLastSavedSpeed.setRequestFocusEnabled(false);

        jLabel21.setText("*cos(");

        textFieldThrottleA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldThrottleA.setText("80");
        textFieldThrottleA.setEnabled(false);
        textFieldThrottleA.setFocusable(false);
        textFieldThrottleA.setMaximumSize(new java.awt.Dimension(24, 20));
        textFieldThrottleA.setMinimumSize(new java.awt.Dimension(24, 20));
        textFieldThrottleA.setPreferredSize(new java.awt.Dimension(24, 20));

        jLabel22.setText("*t)");

        textFieldThrootleW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldThrootleW.setText("0.005");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Engine");

        btnSetSpeed.setText("Set");
        btnSetSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetSpeedActionPerformed(evt);
            }
        });

        btnSetThrottle.setText("Set");
        btnSetThrottle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetThrottleActionPerformed(evt);
            }
        });

        btnSetManualThrottle.setText("Set");
        btnSetManualThrottle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetManualThrottleActionPerformed(evt);
            }
        });

        lblActualVoltage.setText("0 V");
        lblActualVoltage.setFocusable(false);
        lblActualVoltage.setRequestFocusEnabled(false);

        lblError.setFocusable(false);
        lblError.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(toggleBtnEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnCommandLeverSensorDeactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCommandLeverSensorActivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCommandLeverSensorStopAcceleration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCommandLeverSensorResume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCommandLeverSensorStartAcceleration))))
                                    .addGap(75, 75, 75)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(toggleBtnTopGear, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCurrSpped, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblError)
                                        .addComponent(lblActualVoltage)
                                        .addComponent(lblACCSVoltage)
                                        .addComponent(lblLastSavedSpeed))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel13)))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldSpeed)
                                    .addComponent(textFieldThrottle)
                                    .addComponent(textFieldThrottleA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldSpeedA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(textFieldThrootleW)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textFieldSpeedW, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSetManualSpeed)
                                    .addComponent(btnSetManualThrottle)
                                    .addComponent(btnSetThrottle)
                                    .addComponent(btnSetSpeed)))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(toggleBtnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleBtnEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleBtnTopGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommandLeverSensorActivate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommandLeverSensorDeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommandLeverSensorStartAcceleration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommandLeverSensorStopAcceleration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommandLeverSensorResume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleBtnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCurrSpped, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(lblLastSavedSpeed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(lblACCSVoltage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(lblActualVoltage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(lblError)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(textFieldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(btnSetManualSpeed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldThrottle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(btnSetManualThrottle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldSpeedA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(textFieldSpeedW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel10)
                                    .addComponent(btnSetSpeed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(textFieldThrottleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(textFieldThrootleW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(btnSetThrottle))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommandLeverSensorActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandLeverSensorActivateActionPerformed
        btnCommandLeverSensorActivate.setEnabled(false);
        btnCommandLeverSensorDeactivate.setEnabled(true);
        btnCommandLeverSensorStartAcceleration.setEnabled(true);
        btnCommandLeverSensorResume.setEnabled(true);
}//GEN-LAST:event_btnCommandLeverSensorActivateActionPerformed

    private void btnCommandLeverSensorResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandLeverSensorResumeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnCommandLeverSensorResumeActionPerformed

    private void btnCommandLeverSensorStopAccelerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandLeverSensorStopAccelerationActionPerformed
        btnCommandLeverSensorStartAcceleration.setEnabled(true);
        btnCommandLeverSensorStopAcceleration.setEnabled(false);

        // TODO:
}//GEN-LAST:event_btnCommandLeverSensorStopAccelerationActionPerformed

    private void btnCommandLeverSensorStartAccelerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandLeverSensorStartAccelerationActionPerformed
        btnCommandLeverSensorStartAcceleration.setEnabled(false);
        btnCommandLeverSensorStopAcceleration.setEnabled(true);

        // TODO:
}//GEN-LAST:event_btnCommandLeverSensorStartAccelerationActionPerformed

    private void btnCommandLeverSensorDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandLeverSensorDeactivateActionPerformed
        btnCommandLeverSensorActivate.setEnabled(true);
        setCommandLeverButtons(false);
}//GEN-LAST:event_btnCommandLeverSensorDeactivateActionPerformed

    private void btnSetManualSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetManualSpeedActionPerformed
        try {
            int speed = Integer.parseInt(textFieldSpeed.getText());
        } catch (Exception e) {
            System.out.print("not integer");
        }
}//GEN-LAST:event_btnSetManualSpeedActionPerformed

    private void toggleBtnTopGearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtnTopGearActionPerformed
        topGearEngaged = toggleBtnTopGear.isSelected();

        if (topGearEngaged) {
            toggleBtnTopGear.setText(strTopGearDisengaged);
        } else {
            toggleBtnTopGear.setText(strTopGearEngaged);
        }

        if (engineOn) {
            btnCommandLeverSensorActivate.setEnabled(topGearEngaged);
            setCommandLeverButtons(false);
        }
}//GEN-LAST:event_toggleBtnTopGearActionPerformed

    private void toggleBtnEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtnEngineActionPerformed
        if (toggleBtnTopGear.isSelected() || toggleBtnBrake.isSelected()) {
            setErrorMsg("Release brake or Disengage top gear to get engine started!");
        } else {
            clearErrorMsg();

            if (!engineOn) {
                toggleBtnEngine.setText(strStopEngine);
            } else {
                toggleBtnEngine.setText(strStartEngine);

                toggleBtnTopGear.setText(strTopGearEngaged);
                toggleBtnTopGear.setSelected(false);

                toggleBtnBrake.setText(strApplyBrake);
                toggleBtnBrake.setSelected(false);

                btnCommandLeverSensorActivate.setEnabled(false);
                setCommandLeverButtons(false);
            }

            engineOn = !engineOn;
        }
}//GEN-LAST:event_toggleBtnEngineActionPerformed

    private void toggleBtnBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtnBrakeActionPerformed
        brakeApplied = toggleBtnBrake.isSelected();

        if (brakeApplied) {
            toggleBtnBrake.setText(strReleaseBrake);
        } else {
            toggleBtnBrake.setText(strApplyBrake);
        }

        if (engineOn && topGearEngaged) {
            btnCommandLeverSensorActivate.setEnabled(!brakeApplied);
            setCommandLeverButtons(false);
        }
}//GEN-LAST:event_toggleBtnBrakeActionPerformed

    private void btnSetSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetSpeedActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnSetSpeedActionPerformed

    private void btnSetThrottleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetThrottleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnSetThrottleActionPerformed

    private void btnSetManualThrottleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetManualThrottleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnSetManualThrottleActionPerformed

    private void setCommandLeverButtons(boolean checked) {
        btnCommandLeverSensorDeactivate.setEnabled(checked);
        btnCommandLeverSensorStartAcceleration.setEnabled(checked);
        btnCommandLeverSensorStopAcceleration.setEnabled(checked);
        btnCommandLeverSensorResume.setEnabled(checked);
    }

    private boolean canEngageTopGear(int currSpeed) {
        return currSpeed >= 105 || currSpeed <= 130;
    }

    /*
     * methods that ACCSGUI updated GUI
     */
    private void setCurrentSpped(int speed) {
        lblCurrSpped.setText("" + speed);
    }

    private void setSavedSpped(int speed) {
        lblLastSavedSpeed.setText("" + speed + " km/h");
    }

    private void setACCSVoltage(int voltage) {
        double v = (double) voltage / 10.0;
        lblACCSVoltage.setText("" + v + " V");
    }

    private void setActualVoltage(int voltage) {
        double v = (double) voltage / 10.0;
        lblActualVoltage.setText("" + v + " V");
    }

    private void setErrorMsg(String msg) {
        lblError.setText(msg);
    }

    private void clearErrorMsg() {
        lblError.setText("");
    }

    /*
     * methods for GUI to access ACCSGUI ports
     */
    private void setEgineOn() {
        // TODO
    }

    private void setEgineOff() {
        // TODO
    }

    private void setBrakeOn() {
        // TODO
    }

    private void setBrakeOff() {
        // TODO
    }

    private void setTopGearOn() {
        // TODO
    }

    private void setTopGearOff() {
        // TODO
    }

    private void setCommand(int command) {
        // TODO
        switch (command) {
            case commandActivate:
                break;
            case commandDeactivate:
                break;
            case commandStartAcc:
                break;
            case commandStopAcc:
                break;
            case commandResume:
                break;
        }
    }

    private void setManualThrottle(int voltage) {
        // TODO
    }

    private void setManualSpeed(int speed) {
        // TODO
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommandLeverSensorActivate;
    private javax.swing.JButton btnCommandLeverSensorDeactivate;
    private javax.swing.JButton btnCommandLeverSensorResume;
    private javax.swing.JButton btnCommandLeverSensorStartAcceleration;
    private javax.swing.JButton btnCommandLeverSensorStopAcceleration;
    private javax.swing.JButton btnSetManualSpeed;
    private javax.swing.JButton btnSetManualThrottle;
    private javax.swing.JButton btnSetSpeed;
    private javax.swing.JButton btnSetThrottle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblACCSVoltage;
    private javax.swing.JLabel lblActualVoltage;
    private javax.swing.JLabel lblCurrSpped;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLastSavedSpeed;
    private javax.swing.JTextField textFieldSpeed;
    private javax.swing.JTextField textFieldSpeedA;
    private javax.swing.JTextField textFieldSpeedW;
    private javax.swing.JTextField textFieldThrootleW;
    private javax.swing.JTextField textFieldThrottle;
    private javax.swing.JTextField textFieldThrottleA;
    private javax.swing.JToggleButton toggleBtnBrake;
    private javax.swing.JToggleButton toggleBtnEngine;
    private javax.swing.JToggleButton toggleBtnTopGear;
    // End of variables declaration//GEN-END:variables
}
